name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sunucuya SSH ile Bağlan ve Lokal Build Al
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Sunucudaki proje klasörüne git
            cd /home/${{ secrets.SERVER_USER }}/projenin-klasor-adi
            
            # 2. Sunucuda Git üzerindeki en güncel kodları çek
            git pull origin main
            
            # 3. Docker Compose ile imajları sunucunun kendi içinde sıfırdan build et ve ayağa kaldır
            docker compose down
            docker compose up -d --build
            
            # 4. Eski ve boşa çıkan imajları temizle
            docker image prune -f